### ISSUE TITLE
Event design components identified (code of conduct, pre-team huddle etc)

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Community-Gatherings#1]
[ ] Code of Conduct

**Comment by francjp** [comment]
We can use something similar to what we use at FOSDEM and/or LS. Perhaps asking help to Larissa?

**Links**:
- https://github.com/mozilla/participation-org/blob/master/global_events/leadership_summit/code-of-conduct.md
- https://public.etherpad-mozilla.org/p/MozDevRoomCoCProject

**Comment by francjp** [comment]
Code of Conduct / Event Guidelines draft:
https://docs.google.com/document/d/1Ahq-8DqLqpqhboKGaqtJGUmHyrDVs3GqVMfJCltbhHY/edit?usp=sharing

**Comment by francjp** [comment]
Open a new issue for Emergency plan.
