### ISSUE TITLE
Pre-event volunteer survey sent

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Community-Gatherings#11]

**Comment by francjp** [comment]
Survey for after Whistler: https://docs.google.com/a/mozilla.com/forms/d/1hBO1m0gynqzgj6roG2F8953WOWDadQjGKpLsSxOhbUc/edit#
Survey for after Mozfest: https://docs.google.com/a/mozilla.com/forms/d/1VtdGYFeAYHe3glevHkUjfHSFFTcpmufhE4d9AcadN1w/edit?usp=drive_web

This can help as well to create a pre-event. I can came up with a draft if necessary

**Comment by nukeador** [comment]
@francjp do we have pre-event surveys from previous events as well?

**Comment by francjp** [comment]
This: https://docs.google.com/forms/d/1CKlz7ANTLvrudSEkutgK3erLs6PeJC7x5idkLDn7EWs/viewform?usp=send_form

Is the only pre-event survey we have in Drive. I'm afraid that there's the only one we have there, but perhaps we have another on a different platform.
