### ISSUE TITLE
Safety & Privacy components identified

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Community-Gatherings#2]
- [x] Safety Guidelines
- [x] Emergency Plan

**Comment by francjp** [comment]
Safety Guidelines or Code of Conduct:
https://docs.google.com/document/d/1Ahq-8DqLqpqhboKGaqtJGUmHyrDVs3GqVMfJCltbhHY/edit?usp=sharing

**Comment by francjp** [comment]
Emergency plan draft: https://docs.google.com/document/d/1Ds_FlWpjYPwVhTqfFHMzea-KFLhGZtPpap-5yFC8JcE/edit?usp=sharing
Needs to be polished
