### ISSUE TITLE
Meal Planning Proposed

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Community-Gatherings#21]
Each dinner will be up to each group. Let's pre-book: 
- [x] One P-Team volunteer + staff dinner

**Comment by francjp** [comment]
Hi Lucy,

Can you explain this one?, I don't understand what's the plan.

If we want to book places, I have to know how many people are we talking, which dates, and specially, we need to check with Brianna if there will be an All Hands dinner in the middle of the week (like happened in Orlando, for example).

If it's open to all volunteers, we need to set up some sort of registration (basically to be aware of allergies and food restrictions).

From what I know, Mozilla will give some sort of vouchers to volunteers, so perhaps we can try to suggest a couple of places and divide our team to meet with the volunteers?

Cheers,

**Comment by francjp** [comment]
Ok, we have clarity on this point, and how we will be handling this.

However, we need to define if we will be organizing a group/team dinner, and for how many people. We will staff managing reservations on Monday.

**Comment by geroter** [comment]
Can we somehow connect with Hermina Condei to get a dinner coordinated with the Open Innovation Group. Not sure if that's part of this issue or should be a separate one on its own.

**Comment by francjp** [comment]
List of restaurants in the area:
https://docs.google.com/spreadsheets/d/1heHmcA9i-stiebOUjFT6eIcjrNBVjYkxfEHeVaF_tQ4/edit?usp=sharing
Need to be polished and reviewed with SH team.

I'll connect with Hermina to check which dates they have available to meet all together.

Cheers,

**Comment by francjp** [comment]
Staff dinner on Wednesday (with Innovation team)
Open on Tuesday and Thursday, list of options indicated in the comment above.

**Comment by francjp** [comment]
Sent email to Hermina and emails to the restaurants to check availability and space

**Comment by francjp** [comment]
Just to clarify: we have the list of the restaurants (we need to communicate this to vols), and I'm in conversations with 2 places (since the third doesn't have enough space).
Staff dinner will be Wednesday 15th at 8 PM (Participation+Innovation team: 30 people).

Places are already informed about allergies and food restrictions. Hopefully get the confirmation at the beginning of next week.
