### ISSUE TITLE
Mozfest Strategy is Created

### ISSUE THREAD

**Issue by emmairwin** [mozilla/Community-Gatherings#31]
Based on Berlin, identify a strategy moving forward that:
1.  Includes collaboration and scheduled discussion with volunteer leads - Mayur and Priyanka
2.  Builds on interviews from MozRetreat for roles & skills needed in each space.
3.  Designs invitations to apply for roles as part of a robust application process that builds on learning from application processes in the past.
4.  Explains how sessions fit into the application process (if they do) this year.
5.  Includes Comms with space-wranglers, Mozfest leads and our team.
6.  Brings opportunity innovation and creativity to the entire process

**Comment by emmairwin** [comment]
completed

**Comment by ioana-chiorean** [comment]
Hey @emmairwin - is this something we can share in the Weekly reps call? I think people will be interested to hear how things went in Berlin and how we plan our participation at MozFest. . cc @couci
