### ISSUE TITLE
We can describe the function of Participation at Mozfest and have early communication out

### ISSUE THREAD

**Issue by emmairwin** [mozilla/Community-Gatherings#45]
### Document the function of participation at Mozfest in 2016
- [x] Draft - Role definition 
### Prepare clear comms for Mozillians leading up to the Call for Proposals
- [x] Write a blog post that shares goals, and answers some expected questions from Mozillians about the call for proposals, application process and which introduces Mayur & Priyanka + directs further questions to FAQ  (Emma  before June 1)

**Comment by emmairwin** [comment]
Role Definition https://docs.google.com/document/d/1Kdv8JFDzYIilzKPBmUafxbhUxnuoHOlqq1-HQGfD-uM/edit

**Comment by ioana-chiorean** [comment]
This is now taken under @brianking  and @priyankana's wing

**Comment by ioana-chiorean** [comment]
Not sure why @emmairwin was unassigned (I have no right in this repo do do this)
